### PR TITLE
Added setup.py and requirments.txt

### PR DESCRIPTION
**Pull request by hpanago**
And besides, those a .gitignore for python and the do_EOF def at image_browser.py

### CODE REVIEW

**Comment by operatorequals** [comment]
Hey, that's nice ma'am.
Could you please also add the 
```python
entry_points = {
'console_scripts' : ["blah:main",...]
}
```
to `setup.py` ?
This way the installed main scripts will be automatically added to the PATH

**Comment by hpanago** [comment]
Sure, are my changes correct?

Thanks.

**Comment by operatorequals** [comment]
Tried building and installing?

**Comment by operatorequals** [comment]
The `libs/` directory is nowhere to be found...
It should be in `satori/satori/libs`.

**Pull request merged**
